### ISSUE TITLE
Embedding dimensions

### ISSUE THREAD

**Issue by SaisaiSun** [Bruce-ywj/ERNIE-RNA#4]
Hi, I have run 'python extract_embedding.py --seqs_path='./data/test.txt' --device='cuda:0'' to get the embeddings of one RNA sequence (length is 30nt). Here is what I got.
![test](https://github.com/Bruce-ywj/ERNIE-RNA/assets/72762032/62634d2b-d403-4683-b20d-f799c974754d)
![embed_dimension](https://github.com/Bruce-ywj/ERNIE-RNA/assets/72762032/92abe3e2-c4ba-4e78-b2bd-b6afbd270d1c)
But I thought the dimensions should be: attnmap: 156x30x30, all_embedding: 12x30x768, which made me confused. Could you help me explaining it? Thank you!

**Comment by Bruce-ywj** [comment]
@SaisaiSun 
Thank you very much for your question.

When the input sequence length is 30nt, we will add two special tokens at the beginning and end, which are the cls token and eos token, respectively. Therefore, the model output length is L+2.

The previous code extracted the embedding from the last layer by default, so the size of "all_embedding" is (1,32,768). Now I have updated the code to extract embeddings from all layers, with a size of (1,12,32,768); the corresponding attnmap size is (1,156,32,32). The latest modifications can be referred to in extract_embedding.py.

**Comment by SaisaiSun** [comment]
Thank you so much!
