### ISSUE TITLE
Hello, can you post the training code? Thank you

### ISSUE THREAD

**Issue by xhl-xhl** [Bruce-ywj/ERNIE-RNA#5]
Hello, can you post the training code? Thank you

**Comment by kevin-liuguang** [comment]
Hello, did you find the training code？

**Comment by kevin-liuguang** [comment]
Hi @xhl-xhl !
Did you find the training code？

**Comment by Shuo-Zhan** [comment]
We are working on creating a simple, ready-to-run training code. Once it's done, we will upload it to GitHub.
